rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: J1
    pid: {p: 10, i: 0.01, d: 0.1}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: J2
    pid: {p: 10, i: 0.01, d: 0.1}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: J3
    pid: {p: 10, i: 0.01, d: 0.1}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: J5
    pid: {p: 10, i: 0.01, d: 0.1}
