rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: j1
    pid: {p: 150, i: 0.00, d: 20}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: j2
    pid: {p: 150, i: 0.00, d: 20}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: j3
    pid: {p: 150, i: 0.001, d: 20}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: j4
    pid: {p: 1500, i: 10, d: 100, i_clamp: 1000}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: j5
    pid: {p: 150, i: 0.00, d: 20}

